import { Product } from '@/types'; // doesnt represnt schema type

// Note : this is test data and will be deleted

export const SAMPLE_PRODUCTS: Product[] = [
    // Beverages
    {
        id: '1',
        name: 'Coca Cola',
        brand: 'Coca-Cola',
        code: 'BEV-001',
        category: 'Beverages',
        price: 2.5,
        stock: 24,
        unit: 'pcs',
        size: '500ml',
        lowStockThreshold: 10,
        isLowStock: false,
        isOut: false,
        quantityText: '24 pcs',
        description: 'Classic Coca Cola soft drink',
        inCart: 0,
    },
    {
        id: '2',
        name: 'Sprite',
        brand: 'Coca-Cola',
        code: 'BEV-002',
        category: 'Beverages',
        price: 2.5,
        stock: 18,
        unit: 'pcs',
        size: '500ml',
        lowStockThreshold: 10,
        isLowStock: false,
        isOut: false,
        quantityText: '18 pcs',
        description: 'Lemon-lime flavored soft drink',
        inCart: 0,
    },
    {
        id: '3',
        name: 'Fanta Orange',
        brand: 'Coca-Cola',
        code: 'BEV-003',
        category: 'Beverages',
        price: 2.3,
        stock: 20,
        unit: 'pcs',
        size: '500ml',
        lowStockThreshold: 10,
        isLowStock: false,
        isOut: false,
        quantityText: '20 pcs',
        description: 'Orange flavored soft drink',
        inCart: 1,
    },
    {
        id: '4',
        name: "Lay's Classic",
        brand: "Lay's",
        code: 'SNK-001',
        category: 'Snacks',
        price: 1.99,
        stock: 30,
        unit: 'pcs',
        size: '150g',
        lowStockThreshold: 15,
        isLowStock: false,
        isOut: false,
        quantityText: '30 pcs',
        description: 'Original salted potato chips',
        inCart: 0,
    },
    {
        id: '5',
        name: 'Doritos Nacho',
        brand: 'Doritos',
        code: 'SNK-002',
        category: 'Snacks',
        price: 2.25,
        stock: 15,
        unit: 'pcs',
        size: '200g',
        lowStockThreshold: 15,
        isLowStock: true,
        isOut: false,
        quantityText: '15 pcs',
        description: 'Nacho cheese flavored tortilla chips',
        inCart: 0,
    },
    {
        id: '6',
        name: 'Fresh Milk',
        brand: 'Dairy Farm',
        code: 'DRY-001',
        category: 'Dairy',
        price: 3.5,
        stock: 12,
        unit: 'ltr',
        size: '1L',
        lowStockThreshold: 10,
        isLowStock: false,
        isOut: false,
        quantityText: '12 ltr',
        description: 'Fresh whole milk',
        inCart: 0,
    },
    {
        id: '7',
        name: 'Greek Yogurt',
        brand: 'Chobani',
        code: 'DRY-002',
        category: 'Dairy',
        price: 4.25,
        stock: 8,
        unit: 'pcs',
        size: '500g',
        lowStockThreshold: 10,
        isLowStock: true,
        isOut: false,
        quantityText: '8 pcs',
        description: 'Plain Greek yogurt',
        inCart: 0,
    },
    {
        id: '8',
        name: 'White Bread',
        brand: 'Wonder',
        code: 'BKY-001',
        category: 'Bakery',
        price: 2.99,
        stock: 20,
        unit: 'pcs',
        size: '750g',
        lowStockThreshold: 10,
        isLowStock: false,
        isOut: false,
        quantityText: '20 pcs',
        description: 'Soft white sandwich bread',
        inCart: 0,
    },
    {
        id: '9',
        name: 'Red Apples',
        brand: 'Fresh Farm',
        code: 'FRT-001',
        category: 'Fruits',
        price: 4.5,
        stock: 25,
        unit: 'kg',
        size: '1kg',
        lowStockThreshold: 15,
        isLowStock: false,
        isOut: false,
        quantityText: '25 kg',
        description: 'Fresh red apples',
        inCart: 0,
    },
    {
        id: '10',
        name: 'Bananas',
        brand: 'Fresh Farm',
        code: 'FRT-002',
        category: 'Fruits',
        price: 2.99,
        stock: 30,
        unit: 'kg',
        size: '1kg',
        lowStockThreshold: 15,
        isLowStock: false,
        isOut: false,
        quantityText: '30 kg',
        description: 'Fresh ripe bananas',
        inCart: 0,
    },
    {
        id: '11',
        name: 'Carrots',
        brand: 'Garden Fresh',
        code: 'VEG-001',
        category: 'Vegetables',
        price: 1.99,
        stock: 40,
        unit: 'kg',
        size: '1kg',
        lowStockThreshold: 20,
        isLowStock: false,
        isOut: false,
        quantityText: '40 kg',
        description: 'Fresh organic carrots',
        inCart: 0,
    },
    {
        id: '12',
        name: 'Chicken Breast',
        brand: 'Farm Fresh',
        code: 'MET-001',
        category: 'Meat',
        price: 8.99,
        stock: 15,
        unit: 'kg',
        size: '1kg',
        lowStockThreshold: 10,
        isLowStock: false,
        isOut: false,
        quantityText: '15 kg',
        description: 'Fresh chicken breast',
        inCart: 0,
    },
    {
        id: '13',
        name: 'Frozen Peas',
        brand: 'Arctic Fresh',
        code: 'FRZ-001',
        category: 'Frozen',
        price: 3.49,
        stock: 25,
        unit: 'pcs',
        size: '500g',
        lowStockThreshold: 15,
        isLowStock: false,
        isOut: false,
        quantityText: '25 pcs',
        description: 'Frozen green peas',
        inCart: 0,
    },
    {
        id: '14',
        name: 'Dish Soap',
        brand: 'Clean Master',
        code: 'HSE-001',
        category: 'Household',
        price: 2.99,
        stock: 20,
        unit: 'pcs',
        size: '500ml',
        lowStockThreshold: 10,
        isLowStock: false,
        isOut: false,
        quantityText: '20 pcs',
        description: 'Lemon scented dish soap',
        inCart: 0,
    },
    {
        id: '15',
        name: 'Shampoo',
        brand: 'Hair Care Pro',
        code: 'PER-001',
        category: 'Personal Care',
        price: 6.99,
        stock: 18,
        unit: 'pcs',
        size: '400ml',
        lowStockThreshold: 10,
        isLowStock: false,
        isOut: false,
        quantityText: '18 pcs',
        description: 'Moisturizing shampoo for all hair types',
        inCart: 0,
    },
];

export const inventoryData = [
    {
        id: '1',
        name: 'Festive Bread',
        category: 'Bakery',
        type: 'Festive',
        price: 2.99,
        quantity: 3,
        unit: '400g',
        isLowStock: true,
        quantityText: 'loaves',
    },
    {
        id: '2',
        name: 'Simba Chips',
        category: 'Snacks',
        type: 'Simba',
        price: 1.69,
        quantity: 8,
        unit: '50g',
        isLowStock: true,
        quantityText: 'packs',
    },
    {
        id: '3',
        name: 'Apples',
        category: 'Fruits',
        type: 'Imported',
        price: 4.99,
        quantity: 12,
        unit: '1kg',
        isLowStock: false,
        isOut: false,
        isOrdered: false,
        quantityText: 'kg',
    },
    {
        id: '4',
        name: 'Bananas',
        category: 'Fruits',
        type: 'Local',
        price: 1.29,
        quantity: 18,
        unit: '1kg',
        isLowStock: false,
        isOut: true, // Out of stock
        isOrdered: false,
        quantityText: 'bunches',
    },
    {
        id: '5',
        name: 'Beef Steak',
        category: 'Meat',
        type: 'Local',
        price: 12.0,
        quantity: 6,
        unit: '1kg',
        isLowStock: false,
        isOut: false,
        isOrdered: false,
        quantityText: 'kg',
    },
    {
        id: '6',
        name: 'Blue Band Margarine',
        category: 'Household',
        type: 'Blue Band',
        price: 3.5,
        quantity: 10,
        unit: '500g',
        isLowStock: false,
        isOut: false,
        isOrdered: true, // Ordered
        quantityText: 'tubs',
    },
    {
        id: '7',
        name: 'Coca Cola',
        category: 'Beverages',
        type: 'Coca-Cola',
        price: 2.5,
        quantity: 24,
        unit: '500ml',
        isLowStock: false,
        isOut: false,
        isOrdered: true, // Ordered
        quantityText: 'bottles',
    },
];
